# Common
mod.supported_versions = 1.20,1.20.1
deps.parchment_version = 1.20.1
deps.parchment_snapshot = 2023.09.03

deps.modernnetworking_mc = 1.18.2
deps.cloth_config = 11.1.118
deps.talk_balloons_mc = 1.20.1

# Fabric
mod.mc_dep_fabric = >=1.20 <=1.20.1
deps.modmenu = 7.2.2
deps.fabric_api = 0.92.6+1.20.1
deps.fabric_permissions = 0.3.1

# Neo/Forge
mod.mc_dep_forgelike = [1.20,1.20.2)
deps.kotlinlangforge_loader = 2.0
deps.forge = 47.4.10
deps.neoforge = [UNSUPPORTED]