# Defining XML parsers
systemProp.javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
systemProp.javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
systemProp.javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8192m -Xms8192m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel.threads=8
org.gradle.parallel=true
org.gradle.daemon=false

# Loom Setup
	dgt.loom.mappings = mojmap
	dgt.loom.mappings.flavor = parchment

# Mod Properties
	mod.version = 1.0.0
	mod.group = xyz.bluspring
	mod.name = UnityTranslate
	mod.id = unitytranslate

# Dependencies

### Common
	loader_version=0.16.10

	# https://maven.maxhenkel.de/#/releases/de/maxhenkel/voicechat/voicechat-api
	voicechat_api_version=2.5.0

	# https://github.com/plasmoapp/plasmo-voice/releases
	plasmo_api_version=2.1.2

	# https://modrinth.com/mod/simple-voice-chat/versions?g=1.20.1
	voicechat_version=2.5.27
	# https://modrinth.com/mod/simple-voice-chat/versions?g=1.20.4
 	voicechat_deprecated_version=2.5.22

	kotlin_version=2.0.10
	# https://github.com/Kotlin/kotlinx.coroutines
	kotlin_coroutines_version=1.8.1
	# https://github.com/Kotlin/kotlinx.serialization
	kotlin_serialization_version=1.7.1

	# http://mvn.devos.one/#/snapshots/xyz/bluspring/unitytranslate/UnityTranslateLib
	unitytranslatelib_version = 0.2.6

	# https://github.com/TooTallNate/Java-WebSocket/releases
	java_websocket_version = 1.6.0

	# https://central.sonatype.com/artifact/com.github.jnr/jnr-ffi?smo=true
	jnr_version = 2.2.17

	# https://github.com/Moulberry/MixinConstraints/blob/master/build.gradle.kts#L11
	mixinconstraints_version = 1.0.5

	# https://central.sonatype.com/artifact/io.github.givimad/whisper-jni
	whisper_version = 1.7.1

	# https://mvnrepository.com/artifact/com.microsoft.playwright/playwright
	playwright_version = 1.51.0

### Minecraft
## Version: 1.16.5
	1.16.5.parchment_release = 2022.03.06
	1.16.5.forge_version = 36.2.42
	1.16.5.architectury_version = 1.32.68
	1.16.5.fabric_permissions_version = 0.2-SNAPSHOT
	1.16.5.modmenu_version = 1.16.23

## Version: 1.18.2
	1.18.2.parchment_release = 2022.11.06
	1.18.2.forge_version = 40.3.3
	1.18.2.architectury_version = 4.12.94
	1.18.2.fabric_permissions_version = 0.2-SNAPSHOT
	1.18.2.modmenu_version = 3.2.5

## Version: 1.19.2
	1.19.2.parchment_release = 2022.11.27
	1.19.2.forge_version = 43.4.16
	1.19.2.architectury_version = 6.6.92
	1.19.2.fabric_permissions_version = 0.2-SNAPSHOT
	1.19.2.modmenu_version = 4.2.0-beta.2

## Version: 1.20.1
	1.20.1.parchment_release = 2023.09.03
	1.20.1.forge_version = 47.3.27
	1.20.1.architectury_version = 9.2.14
	1.20.1.fabric_permissions_version = 0.3.1
	1.20.1.modmenu_version = 7.1.0

## Version: 1.20.4
	1.20.4.parchment_release = 2024.04.14
	1.20.4.forge_version = 49.1.29
	1.20.4.neoforge_version = 20.4.239
	1.20.4.architectury_version = 11.1.17
	1.20.4.fabric_permissions_version = 0.3.1
	1.20.4.modmenu_version = 9.2.0-beta.2

## Version: 1.20.6
	1.20.6.parchment_release = 2024.06.16
	1.20.6.forge_version = 50.1.39
	1.20.6.neoforge_version = 20.6.125
	1.20.6.architectury_version = 12.1.4
	1.20.6.fabric_permissions_version = 0.3.1
	1.20.6.modmenu_version = 10.0.0-beta.1

## Version: 1.21.1
	1.21.1.parchment_release = 2024.11.17
	1.21.1.forge_version = 52.0.47
	1.21.1.neoforge_version = 21.1.115
	1.21.1.architectury_version = 13.0.8
	1.21.1.fabric_version = 0.115.0+1.21.1
	1.21.1.fabric_permissions_version = 0.3.1
	1.21.1.modmenu_version = 11.0.1

## Version: 1.21.3
	1.21.3.parchment_release = 2024.12.07
	1.21.3.forge_version = 53.0.44
	1.21.3.neoforge_version = 21.3.62
	1.21.3.architectury_version = 14.0.4
	1.21.3.fabric_version = 0.114.0+1.21.3
	1.21.3.fabric_permissions_version = 0.3.3
	1.21.3.modmenu_version = 12.0.0-beta.1

## Version: 1.21.4
	1.21.4.parchment_release = 2025.01.19
	1.21.4.forge_version = 54.0.26
	1.21.4.neoforge_version = 21.4.81-beta
	1.21.4.architectury_version = 15.0.1
	1.21.4.fabric_version = 0.115.1+1.21.4
	1.21.4.fabric_permissions_version = 0.3.3
	1.21.4.modmenu_version = 13.0.2