org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.caching.debug=false
kotlin.code.style = official

# Project
mod.id = unitytranslate
mod.group = xyz.bluspring
mod.version = 2.0.0
mod.name = UnityTranslate
mod.sources = https://github.com/unprodstudio/UnityTranslate
mod.description = A mod designed for free live translation, inspired by the QSMP. Mainly created for the Unity Multiplayer server, and for public release towards the multilingual Minecraft community.

# Publishing
publishing.modrinth = yA7uge1H
publishing.curseforge = 1093604
