# Defining XML parsers
systemProp.javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
systemProp.javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
systemProp.javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8192m -Xms8192m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Mod Properties
	mod.version = 2.0.0
	mod.group = xyz.bluspring
	mod.name = UnityTranslate
	mod.id = unitytranslate

	# Dependencies

### Common
	deps.fabric_loader=0.16.14
	deps.fabric_kotlin=1.13.4+kotlin.2.2.0

	# https://maven.maxhenkel.de/#/releases/de/maxhenkel/voicechat/voicechat-api
	deps.voicechat_api=2.5.31

	# https://github.com/plasmoapp/plasmo-voice/releases
	deps.plasmo_api=2.1.5

	# https://modrinth.com/mod/simple-voice-chat/versions?g=1.20.1
	deps.voicechat = [VERSIONED]

	deps.kotlin=2.2.0
	# https://github.com/Kotlin/kotlinx.coroutines
	deps.kotlin_coroutines=1.10.2
	# https://github.com/Kotlin/kotlinx.serialization
	deps.kotlin_serialization=1.8.1

	# http://mvn.devos.one/#/snapshots/xyz/bluspring/unitytranslate/UnityTranslateLib
	deps.unitytranslatelib = 0.4.2
	# this is actually just for the submodule.
	unitytranslate_version = 0.4.2

	# https://github.com/TooTallNate/Java-WebSocket/releases
	deps.java_websocket = 1.6.0

	# https://central.sonatype.com/artifact/com.github.jnr/jnr-ffi?smo=true
	deps.jnr = 2.2.17

    # https://central.sonatype.com/artifact/net.java.dev.jna/jna
    deps.jna = 5.17.0

	# https://github.com/Moulberry/MixinConstraints/blob/master/build.gradle.kts#L11
	deps.mixinconstraints = 1.0.9

	# https://central.sonatype.com/artifact/io.github.givimad/whisper-jni
	deps.whisper = 1.7.1

	# https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
	deps.selenium = 4.35.0

	# https://github.com/EssentialGG/Elementa
	deps.elementa = 710
	deps.universalcraft = 421
    # https://github.com/EssentialGG/Vigilance
    deps.vigilance = 312

    # https://github.com/google/gson/releases
    deps.gson = 2.13.1
    # https://mvnrepository.com/artifact/net.sourceforge.javaflacencoder/java-flac-encoder
    deps.java_flac_encoder = 0.3.7

### Minecraft
	mod.parchment_snapshot = [VERSIONED]
	deps.forge = [VERSIONED]
	deps.neoforge = [VERSIONED]
	deps.fabric_api = [VERSIONED]
	deps.modmenu = [VERSIONED]
	deps.modernnetworking_mc = [VERSIONED]
	deps.modernnetworking = 1.2.0
	deps.mixin_extras = 0.4.1
	deps.talk_balloons = 1.3.0
	deps.cloth_config = [VERSIONED]