# Common
mod.supported_versions = 1.21.11
deps.parchment_version = 1.21.10
deps.parchment_snapshot = 2025.10.12

deps.modernnetworking_mc = 1.21.10
deps.cloth_config = 21.11.153
deps.talk_balloons_mc = 1.21.11

# Fabric
mod.mc_dep_fabric = >=1.21.11
deps.modmenu = 16.0.0-rc.1
deps.fabric_api = 0.138.3+1.21.10
deps.fabric_permissions = 0.5.0
deps.plasmo_mc = 1.21.11

# Neo/Forge
mod.mc_dep_forgelike = [1.21.11,)
deps.kotlinlangforge_loader = 3.1
deps.forge = [UNSUPPORTED]
deps.neoforge = 21.11.12-beta