# Common
mod.supported_versions = 1.21.9,1.21.10
deps.parchment_version = 1.21.10
deps.parchment_snapshot = 2025.10.12

deps.modernnetworking_mc = 1.21.10
deps.cloth_config = 20.0.149
deps.talk_balloons_mc = 1.21.10

# Fabric
mod.mc_dep_fabric = >=1.21.9
deps.modmenu = 16.0.0-rc.1
deps.fabric_api = 0.138.3+1.21.10

# Neo/Forge
mod.mc_dep_forgelike = [1.21.9,)
deps.kotlinlangforge_loader = 3.1
deps.forge = [UNSUPPORTED]
deps.neoforge = 21.10.52-beta