# Common
mod.supported_versions = 1.21.4
deps.parchment_version = 1.21.4
deps.parchment_snapshot = 2025.03.23

deps.modernnetworking_mc = 1.21.1
deps.cloth_config = 17.0.144
deps.talk_balloons_mc = 1.21.4

# Fabric
mod.mc_dep_fabric = 1.21.4
deps.modmenu = 13.0.3
deps.fabric_api = 0.119.4+1.21.4
deps.fabric_permissions = 0.3.3

# Neo/Forge
mod.mc_dep_forgelike = [1.21.4,1.21.5)
deps.kotlinlangforge_loader = 3.0
deps.forge = [UNSUPPORTED]
deps.neoforge = 21.4.155