# Common
mod.supported_versions = 1.21.6,1.21.7,1.21.8
deps.parchment_version = 1.21.8
deps.parchment_snapshot = 2025.09.14

deps.modernnetworking_mc = 1.21.1
deps.cloth_config = 19.0.147
deps.talk_balloons_mc = 1.21.6
deps.plasmo_mc = 1.21.6

# Fabric
mod.mc_dep_fabric = >=1.21.6 <=1.21.8
deps.modmenu = 15.0.0
deps.fabric_api = 0.136.1+1.21.8
deps.fabric_permissions = 0.4.1

# Neo/Forge
mod.mc_dep_forgelike = [1.21.6,1.21.9)
deps.kotlinlangforge_loader = 3.0
deps.forge = [UNSUPPORTED]
deps.neoforge = 21.8.51