# Common
mod.supported_versions = 1.21,1.21.1
deps.parchment_version = 1.21.1
deps.parchment_snapshot = 2024.11.17

deps.modernnetworking_mc = 1.21.1
deps.cloth_config = 15.0.140
deps.talk_balloons_mc = 1.21.1
deps.plasmo_mc = 1.21

# Fabric
mod.mc_dep_fabric = >=1.21 <=1.21.1
deps.modmenu = 11.0.3
deps.fabric_api = 0.116.7+1.21.1
deps.fabric_permissions = 0.3.1

# Neo/Forge
mod.mc_dep_forgelike = [1.21,1.21.2)
deps.kotlinlangforge_loader = 3.0
deps.forge = [UNSUPPORTED]
deps.neoforge = 21.1.215