name: Publish JDK 21 Mods
on:
  release:
    types:
      - 'released'

jobs:
  build:
    environment: UnityTranslate Publishing
    name: Publish Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - name: Execute Gradle build
        env:
          GITHUB_TAG: ${{ github.ref_name }}
          RELEASE_DESCRIPTION: ${{ github.event.release.body }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        run: ./gradlew publishMods